### ISSUE TITLE
Button and text labels are missaligned

### ISSUE THREAD

**Issue by WhyNotHugo** [spantaleev/sftpman-gtk#1]
Button and text labels seem quite missaligned. I haven't seen this on other gtk3 apps. My theme is the gtk default (dark variant):

![2014-12-06-151810_1440x900_scrot](https://cloud.githubusercontent.com/assets/730811/5328430/6087e528-7d5b-11e4-8399-80ff26117ea3.png)

[Here](https://github.com/hobarrera/dotfiles/blob/master/home/.config/gtk-3.0/settings.ini)'s my gtkrc. Without it, the issue is not reproducible, it seems like a corner case (however, again, it does not ocurr with other gtk3 apps).

**Comment by spantaleev** [comment]
It's been a super long time, but I finally could get back to fixing stuff on this project.

I believe that 39ced4d105f resolves this problem (part of the `1.0` release), along with some other UI improvements.

Thank you for your patience!
