### ISSUE TITLE
Edit Machine Id

### ISSUE THREAD

**Issue by szmaszmo1** [spantaleev/sftpman-gtk#11]
Currently if I make a mistake by non-editable "Machine Id", I need to type everything again.
It would be great to be able to edit this field as well.

**Comment by spantaleev** [comment]
Despite duplication/cloning being supported (as per #12) and being a viable workaround, I've also made IDs editable.

This feature is part of the `1.3.0` release.

**Comment by szmaszmo1** [comment]
Thank you very much!
