### ISSUE TITLE
Entry duplication

### ISSUE THREAD

**Issue by szmaszmo1** [spantaleev/sftpman-gtk#12]
Since many options are similar in my entries, 
it would be really helpful to have a "duplicate" option (up to Machine Id of course).

This could also be a "workaround" for Machine Id editing.
I could duplicate existing entry giving it a new Machine Id and then simply delete old entry.

**Comment by spantaleev** [comment]
Cloning is now part of the `1.3.0` release.

**Comment by szmaszmo1** [comment]
Thank you very much!
